Native-Planet/GroundSeg

README.md, release/complete_uninstall.sh, release/groundseg_install.sh, release/groundseg_uninstall.sh, release/io.nativeplanet.groundseg.plist, release/io.nativeplanet.gs-pipefile.plist, release/standard_uninstall.sh
=> modified installer to check for macOS

api/app.py, api/orchestrator.py, ui/src/lib/Dropzone.svelte, ui/src/lib/NewPierButtons.svelte, ui/src/lib/SysInfo.svelte, ui/src/lib/api.js
- Fixed issue with large pier upload
- Fixed restarting from the webui results in device shutting down
- Fixed unable to boot new ship
- Fixed pier upload loading bar typo
=> Minor bug fixes

api/app.py, api/orchestrator.py, ui/src/lib/Dropzone.svelte, ui/src/lib/NewPierButtons.svelte, ui/src/lib/SysInfo.svelte, ui/src/lib/api.js
- Improved extraction speed of uploaded pier
- Temporarily disable auto-updates when a pier is being uploaded
- Fixed auto-update toggle sometimes not working
=> Beta-3.2.0

api/app.py, api/orchestrator.py, ui/src/lib/api.js
- Fixed failed pier upload causing file size mismatched error
- Fixed premature restart of auto-updates when uploading pier
=> pier upload bug fixes

api/orchestrator.py, api/urbit_docker.py, ui/src/lib/Dropzone.svelte, ui/src/lib/PierHeader.svelte, ui/src/lib/PierList.svelte, ui/src/lib/api.js, ui/src/routes/boot/existing/+page.svelte
- Improved pier upload error messages in webui
- Fixed cancel button not reappearing in pier upload page
- Fixed link to ship not working on homepage
- Fixed loading animation when toggle pier on/off
- Fixed wireguard turns on after reboot regardless of settings
- Fixed remember Urbit status not working correctly
- Fixed first time packing and melding has delay
=> Beta 3.2.2

api/orchestrator.py, api/webui_docker.py, release/version_edge.csv, ui/src/lib/api.js, ui/src/routes/(home)/+page.server.js, ui/src/routes/(home)/+page.svelte, ui/src/routes/+layout.svelte, ui/src/routes/login/+page.server.js, ui/src/routes/login/+page.svelte
- Fixed cookies not working on non-mdns domain
=> Fixed cookies not working on non-mdns domain

api/orchestrator.py, api/urbit_docker.py, api/webui_docker.py, release/groundseg_install.sh, release/version.csv, release/version_edge.csv, ui/src/lib/PierOptions.svelte, ui/src/lib/PierOptionsAdmin.svelte, ui/src/lib/api.js, ui/src/routes/[patp]/+page.svelte
- Added support for variable loom size
=> Beta-3.3.5

api/mc_docker.py, api/minio_docker.py, api/orchestrator.py, api/urbit_docker.py, api/webui_docker.py, release/version_edge.csv, ui/src/lib/api.js
- Replaced MC binary with docker image
- Fixed typo when deleting StarTram services
- Fixed typo when building Urbit container
=> Beta-3.3.6-edge

api/orchestrator.py, release/version_edge.csv, ui/src/lib/AnchorButton.svelte, ui/src/lib/Logs.svelte, ui/src/lib/NoConnection.svelte, ui/src/lib/api.js, ui/src/routes/(home)/+page.server.js, ui/src/routes/(home)/+page.svelte, ui/src/routes/+layout.svelte, ui/src/routes/[patp]/+page.server.js, ui/src/routes/[patp]/+page.svelte, ui/src/routes/boot/existing/+page.server.js, ui/src/routes/boot/new/+page.server.js, ui/src/routes/login/+page.server.js, ui/src/routes/settings/+page.server.js, ui/src/routes/settings/+page.svelte, ui/src/routes/startram/+page.server.js, ui/src/routes/startram/+page.svelte
- Fixed error when changing StarTram endpoint
- Added check for connection between Web UI and API
=> Beta-3.3.9-edge

api/groundseg.py, api/orchestrator.py, api/webui_docker.py, release/version.csv, release/version_edge.csv, ui/src/lib/SysInfo.svelte, ui/src/lib/api.js
- Added restart GroundSeg button to Web UI.
=> Beta-3.5.1

api/groundseg.py, api/orchestrator.py, api/webui_docker.py, release/groundseg_install.sh, release/version.csv, release/version_edge.csv, ui/src/lib/AnchorButton.svelte, ui/src/lib/SettingsButton.svelte, ui/src/lib/SetupAnchor.svelte, ui/src/lib/SetupPassword.svelte, ui/src/lib/api.js, ui/src/routes/(home)/+page.server.js, ui/src/routes/(home)/+page.svelte, ui/src/routes/[patp]/+page.server.js, ui/src/routes/[patp]/+page.svelte, ui/src/routes/settings/+page.server.js, ui/src/routes/settings/+page.svelte, ui/src/routes/setup/+page.server.js, ui/src/routes/setup/+page.svelte, ui/src/routes/startram/+page.server.js, ui/src/routes/startram/+page.svelte
- Added setup mode
- Removed blur from navigation buttons
=> Beta-3.5.2-edge

api/groundseg.py, api/orchestrator.py, api/webui_docker.py, release/groundseg_install.sh, release/version.csv, release/version_edge.csv, ui/src/lib/AnchorButton.svelte, ui/src/lib/SettingsButton.svelte, ui/src/lib/SetupAnchor.svelte, ui/src/lib/SetupPassword.svelte, ui/src/lib/api.js, ui/src/routes/(home)/+page.server.js, ui/src/routes/(home)/+page.svelte, ui/src/routes/[patp]/+page.server.js, ui/src/routes/[patp]/+page.svelte, ui/src/routes/settings/+page.server.js, ui/src/routes/settings/+page.svelte, ui/src/routes/setup/+page.server.js, ui/src/routes/setup/+page.svelte, ui/src/routes/startram/+page.server.js, ui/src/routes/startram/+page.svelte
- Added setup mode
- Removed blur from navigation buttons
=> Beta-3.5.2

api/orchestrator.py, api/urbit_docker.py, api/wireguard_docker.py, release/version_edge.csv, ui/src/lib/api.js
- Replaced restarting urbit docker container with recreating the container.
- Added internet access check before creating docker containers.
=> Beta-3.5.4-edge

api/orchestrator.py, release/version_edge.csv, ui/src/lib/api.js
- Added wireguard config update upon toggling on.
=> Beta-3.5.5-edge

.gitignore, api/groundseg.py, api/orchestrator.py, api/requirements.txt, build-scripts/Dockerfile, build-scripts/builder.sh, build-scripts/make-image.sh, build.sh, release/groundseg_install.sh, release/version.csv, release/version_edge.csv, ui/src/lib/SysInfoLite.svelte, ui/src/lib/api.js, ui/src/routes/settings/+page.svelte
- Added VM mode
- Fixed ssl issue when checking for internet access
=> Beta-3.5.6-edge

api/groundseg.py, api/orchestrator.py, api/utils.py, release/version_edge.csv, ui/src/lib/BugButton.svelte, ui/src/lib/SysInfoLite.svelte, ui/src/lib/api.js, ui/src/routes/+layout.svelte, ui/src/routes/report-issue/+page.server.js, ui/src/routes/report-issue/+page.svelte, ui/src/routes/startram/+page.svelte
- Added bug report feature
- Split GroundSeg logs by months
=> v1.0.1-edge

README.md, api/groundseg.py, api/orchestrator.py, api/requirements.txt, api/urbit_docker.py, api/utils.py, release/version.csv, release/version_edge.csv, ui/src/lib/api.js
- Replaced tloncorp/urbit docker image with tloncorp/vere docker image
- Run threads as daemon
=> v1.0.4-edge

api/groundseg.py, api/orchestrator.py, api/urbit_docker.py, release/version.csv, release/version_edge.csv, ui/src/lib/AnchorAdvanced.svelte, ui/src/lib/api.js, ui/src/routes/startram/+page.svelte
- Start binary updater thread before orchestrator init.
- Added check for StarTram service creation status before applying to config file.
- Update ship ports when an updated config is retrieved.
- Added StarTram refresher thread to restart wireguard if connection is broken.
- Added manual StarTram restart button to Web UI.
=> v1.0.7-edge

build-scripts/builder.sh
Not sure why this is necessary but it works
=> Fix build script for ARM

Jenkinsfile, release/groundseg_install.sh, release/standard_install.sh
Jenkinsfile and install script updates
=> Fast forward

api/docker_updater.py
Reverts Native-Planet/GroundSeg#142
=> Revert "fix docker tags"

goseg/broadcast/broadcast.go, goseg/config/config.go, goseg/config/version.go, goseg/docker/docker.go, goseg/handler/handler.go, goseg/main.go, goseg/rectify/rectify.go, goseg/structs/broadcast.go, goseg/structs/structs.go, goseg/structs/ws.go, goseg/ws/ws.go, ui/src/routes/ApiSpinner.svelte, ui/src/routes/[patp]/Section/RemoteAccess.svelte, ui/src/routes/profile/Password.svelte, ui/src/routes/system/PowerModal.svelte, ui/src/routes/system/SystemDetails.svelte
- Webui updates
- shutdown/restart
- version update skeleton
- groundseg binary sha256 hash
=> Minor improvements

goseg/system/system.go
=> add mdns collision detection

goseg/main.go, goseg/ws/ws.go
waits for 30 sec of no connection before switching
=> less sensitive c2c switch

goseg/config/config.go, goseg/docker/docker.go, goseg/docker/llama.go
Reverts Native-Planet/GroundSeg#507
=> Revert "V2 goseg reid"

ui/src/routes/boot/new/Free.svelte, ui/src/routes/boot/new/KeyDropper.svelte, ui/src/routes/boot/new/NotFree.svelte
Implements https://github.com/Native-Planet/GroundSeg/issues/596
=> populate ship names from key filename

goseg/importer/extract.go, goseg/importer/importer.go
Fixes #674
Not a go dev, and haven't tested this, but seems like a straightforward patch.
=> Add support for .tgz or .tar extensions

goseg/docker/docker.go, goseg/docker/urbit.go, goseg/handler/urbit.go
=> fix boot behavior after rebuilding vere container
